sudo: required
services:
  - docker

before_install:
  - docker build -t ianjyuxiao/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker -e CI=true run ianjyuxiao/client-test npm test

after_success:
  - docker build -t ianjyuxiao/client ./client
  - docker build -t ianjyuxiao/nginx ./nginx
  - docker build -t ianjyuxiao/server ./server
  - docker build -t ianjyuxiao/worker ./worker
